server:
  port: 1111


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.example.demo.model # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                # mysql驱动包
    url: jdbc:mysql://rm-2ze4tk0u850c64o60o.mysql.rds.aliyuncs.com:3306/ts_manage_center?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull              # 数据库名称
    username: dbuser4test_mc
    password: dbpsw4test_mc_20170511
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

  application:
    name: provider1

eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:7001/eureka/




